### PR TITLE
`copilot-theorem`: Update examples to compile with `copilot-theorem >= 3.0`. Refs #692.

### LINKED ISSUE #692: `copilot-theorem`: Examples do not compile
**Description**

Some example programs in the `copilot-theorem/example` subdirectory have bitrotted, as they depend on a `Copilot.Theorem.Prover.Z3` module that is no longer included in `copilot-theorem.cabal` (as of https://github.com/Copilot-Language/copilot/commit/6a67d89ee42ffa0718e844e03a4e7f34d2a88801). Attempting to build any of these examples results in compilation failures.

**Type**

* Bug: Example programs fail to compile.

**Additional context**

`Copilot.Theorem.Prover.Z3` was an early, SMT solver–based approach for proving properties about Copilot specifications. The `copilot-theorem` library has largely replaced `Copilot.Theorem.Prover.Z3` will different APIs, such as those offered by `Copilot.Theorem.Prover.SMT` and `Copilot.Theorem.What4`. Of the latter two, the API in `Copilot.Theorem.Prover.SMT` is closest to what `Copilot.Theorem.Prover.Z3` offered.

**Requester**

* Ryan Scott (Galois)

**Method to check presence of bug**

First, build the `copilot` libraries, using a method such as the following:

```
$ cabal build copilot --write-ghc-environment-files=always
```

Then invoke `ghc` on one of the files in the `copilot-theorem/examples` subdirectory that import `Copilot.Theorem.Prover.Z3`. The bug manifests as a GHC compilation error, such as in the following example:

```
$ ghc copilot-theorem/examples/BoyerMoore.hs
Loaded package environment from /Users/rscott/Documents/Hacking/Haskell/copilot/.ghc.environment.aarch64-darwin-9.4.8
[1 of 1] Compiling BoyerMoore       ( copilot-theorem/examples/BoyerMoore.hs, copilot-theorem/examples/BoyerMoore.o )

copilot-theorem/examples/BoyerMoore.hs:8:1: error:
    Could not find module ‘Copilot.Theorem.Prover.Z3’
    Perhaps you meant
      Copilot.Theorem.Prover.SMT (from copilot-theorem-4.6)
      Copilot.Theorem.Prover.SMT (needs flag -package-id copilot-theorem-4.3)
      Copilot.Theorem.Prover.SMT (needs flag -package-id copilot-theorem-4.3)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | import Copilot.Theorem.Prover.Z3
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected result**

Invoking `ghc` on any of the examples in the `copilot-theorem/examples` subdirectory should succeed.

**Desired result**

Invoking `ghc` on any of the examples in the `copilot-theorem/examples` subdirectory should succeed.

**Proposed solution**

Modify the code in each of the examples in `copilot-theorem/examples` to import from `Copilot.Theorem.Prover.SMT` instead of `Copilot.Theorem.Prover.Z3`, making adjustments as needed to adapt to the slightly different API in `Copilot.Theorem.Prover.SMT`.

**Further notes**

None.

### PR DESCRIPTION
**Pull request by chathhorn-galois**
Some example programs in the copilot-theorem/example subdirectory have bitrotted, as they depend on a `Copilot.Theorem.Prover.Z3` module that is no longer included in copilot-theorem.cabal (as of 6a67d89). Attempting to build any of these examples results in compilation failures.

This PR updates the examples to use the `Copilot.Theorem.Prover.SMT` module in place of the deprecated `Copilot.Theorem.Prover.Z3` module. With these updates, all of the examples now compile, but with many warnings and not all of the proofs succeed.

Fixes #692.

### CODE REVIEW

File: copilot-theorem/examples/BoyerMoore.hs [hunk 1]
```diff
@@ -5,7 +5,7 @@ module BoyerMoore where
 
 import Copilot.Language hiding (length)
 import Copilot.Theorem
-import Copilot.Theorem.Prover.Z3
+import Copilot.Theorem.Prover.SMT (induction, def, debug, z3)
```
Comment (ivanperez-keera) [inline copilot-theorem/examples/BoyerMoore.hs]: Change Manager: Can you please alphabetize these imports?

File: copilot-theorem/examples/Grey.hs [hunk 2]
```diff
@@ -4,7 +4,7 @@ module Grey where
 
 import Copilot.Language
 import Copilot.Theorem
-import Copilot.Theorem.Prover.Z3
+import Copilot.Theorem.Prover.SMT (def, Options (..), z3, kInduction, induction)
```
Comment (ivanperez-keera) [inline copilot-theorem/examples/Grey.hs]: Change Manager: Can you please alphabetize these imports?

File: copilot-theorem/examples/SerialBoyerMoore.hs [hunk 3]
```diff
@@ -4,7 +4,7 @@ module SerialBoyerMoore where
 
 import Copilot.Language
 import Copilot.Theorem
-import Copilot.Theorem.Prover.Z3
+import Copilot.Theorem.Prover.SMT (def, Options (..), induction, kInduction, z3)
```
Comment (ivanperez-keera) [inline copilot-theorem/examples/SerialBoyerMoore.hs]: Change Manager: Can you please alphabetize these imports?

Types go before functions (I use `stylish-haskell`, which does it that way by default).

File: copilot-theorem/examples/SphericalWCV.hs [hunk 4]
```diff
@@ -8,7 +8,7 @@ import Prelude ()
 import Copilot.Language
 import Copilot.Language.Reify
 import Copilot.Theorem
-import Copilot.Theorem.Prover.Z3
+import Copilot.Theorem.Prover.SMT (def, debug, onlySat, onlyValidity, z3)
```
Comment (ivanperez-keera) [inline copilot-theorem/examples/SphericalWCV.hs]: Change Manager: Can you please alphabetize these imports?

File: copilot-theorem/examples/WCV.hs [hunk 5]
```diff
@@ -5,7 +5,7 @@ import Prelude ()
 import Copilot.Language
 import Copilot.Language.Reify
 import Copilot.Theorem
-import Copilot.Theorem.Prover.Z3
+import Copilot.Theorem.Prover.SMT (def, debug, onlySat, onlyValidity, z3)
```
Comment (ivanperez-keera) [inline copilot-theorem/examples/WCV.hs]: Change Manager: Can you please alphabetize these imports?

File: copilot-theorem/CHANGELOG [hunk 6]
```diff
@@ -1,3 +1,6 @@
+2026-03-31
+        * Fix examples so they compile with latest copilot-theorem. (#692)
```
Comment (ivanperez-keera) [inline copilot-theorem/CHANGELOG]: Can you please change this entry to (3.0 was where the Z3 module disappeared):

```
2026-03-31
        * Update examples to compile with copilot-theorem >= 3.0. (#692)
```

**Comment by ivanperez-keera** [comment]
Change Manager:
- Please address the comments in the review.
- Please change the first line of the first commit message to:
```
copilot-theorem: Update examples to compile with copilot-theorem >= 3.0. Refs #692.
```
- Please rebase your commits on top of the current `HEAD` in the `master` branch.

**Review by ivanperez-keera — CHANGES_REQUESTED** [review]

**Comment by chathhorn-galois** [comment]
Implementor: Fix implemented, review requested.

**Review by ivanperez-keera — APPROVED** [review]

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:
- Solution is implemented:
  - [X] The code proposed compiles and passes all tests. Details:
    Build log: https://app.travis-ci.com/github/Copilot-Language/copilot/builds/278077300
  - [X] The solution proposed produces the expected result. Details:
    The following Dockerfile checks that all the examples that used the removed module `Z3` can now be compiled, after which it prints the message "Success":
    ```Dockerfile
    FROM ubuntu:jammy
    
    WORKDIR /root
    SHELL ["/bin/bash", "-c"]
    
    ENV DEBIAN_FRONTEND=noninteractive
    RUN apt-get update
    
    RUN apt-get install --yes \
          libz-dev \
          git \
          curl \
          gcc \
          g++ \
          make \
          libgmp3-dev  \
          pkg-config
    
    RUN mkdir -p $HOME/.ghcup/bin
    RUN curl https://downloads.haskell.org/~ghcup/0.1.40.0/x86_64-linux-ghcup-0.1.40.0 -o $HOME/.ghcup/bin/ghcup
    RUN chmod a+x $HOME/.ghcup/bin/ghcup
    ENV PATH=$PATH:/root/.ghcup/bin/
    ENV PATH=$PATH:/root/.cabal/bin/
    
    RUN ghcup install ghc 9.8.4
    RUN ghcup install cabal 3.2
    RUN ghcup set ghc 9.8.4
    RUN cabal update
    
    CMD git clone $REPO && cd $NAME && git checkout $COMMIT && cd .. \
      && cabal v1-sandbox init \
      && cabal v1-install alex happy --constraint='happy <= 2' \
      && cabal v1-install \
           $NAME/copilot/ \
           $NAME/copilot-c99/ \
           $NAME/copilot-core/ \
           $NAME/copilot-prettyprinter/ \
           $NAME/copilot-interpreter/ \
           $NAME/copilot-language/ \
           $NAME/copilot-libraries/ \
           $NAME/copilot-theorem/ \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/BoyerMoore.hs \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/Grey.hs \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/Incr.hs \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/SerialBoyerMoore.hs \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/SphericalWCV.hs \
      && cabal v1-exec -- ghc -XGADTs -c $NAME/copilot-theorem/examples/WCV.hs \
      && echo "Success"
    ```
    Command (substitute variables based on new path after merge):
    ```
    $ docker run -e REPO=https://github.com/GaloisInc/copilot-1 -e NAME=copilot-1 -e COMMIT=579b124a56146f563e620ca9df5d9b1c70640a84 copilot-verify-692
    ```
- [X] Implementation is documented. Details:
  No updates needed; the changes are minimal maintenance updates to examples.
- [X] Change history is clear.
- [X] Commit messages are clear.
- [X] Changelogs are updated.
- [X] Examples are updated. Details:
  The change is to the examples.
- [X] Required version bumps are evaluated. Details:
  Bump not required; change affects examples only.
