### ISSUE TITLE
Failure to compile with GHC >= 8.4

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot#212]
This library depends on pretty-ncols, which fails to compile with versions of GHC >= 8.4 (base >= 4.11) because `Prelude` exports `(<>)`, which conflicts with `Text.PrettyPrint.<>`:

```
Preprocessing library pretty-ncols-0.1...
[1 of 1] Compiling Text.PrettyPrint.NCol ( Text/PrettyPrint/NCol.hs, dist/dist-sandbox-11467d12/build/Text/PrettyPrint/NCol.o )

Text/PrettyPrint/NCol.hs:27:25: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Text/PrettyPrint/NCol.hs:1:8-28
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Text/PrettyPrint/NCol.hs:4:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
27 |         where buf x = x <> (hcat $ replicate q space) <> (hcat $ replicate (mx - (docLen x)) space)
   |                         ^^

Text/PrettyPrint/NCol.hs:27:55: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Text/PrettyPrint/NCol.hs:1:8-28
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Text/PrettyPrint/NCol.hs:4:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
27 |         where buf x = x <> (hcat $ replicate q space) <> (hcat $ replicate (mx - (docLen x)) space)
   |                                                       ^^
cabal: Leaving directory '/tmp/cabal-tmp-19047/pretty-ncols-0.1'
Failed to install pretty-ncols-0.1
cabal: Entering directory '/tmp/cabal-tmp-19047/random-1.1'
```

Pretty-ncols is not on github and has not been updated in a very long time. I just sent an email to the author.
