### ISSUE TITLE
Failure to compile with GHC 8.6

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot#102]
The copilot3.0-dev branch fails to compile with GHC 8.6/base-4.12:
```
src/Copilot/Theorem/TransSys/Spec.hs:129:6: error:
    • Data.Map.fold is gone. Use foldr.
```

It compiles fine with GHC 8.4/base-4.11.
